-- ============================================================================
-- schema.sql — ESQUEMA COMPLETO DE LA BASE DE DATOS (PostgreSQL / Supabase)
-- ----------------------------------------------------------------------------
-- Es IDEMPOTENTE: se puede ejecutar cuantas veces se quiera (CREATE ... IF NOT
-- EXISTS). Se ejecuta con:   npm run db:migrar
-- o pegándolo completo en Supabase -> SQL Editor -> Run.
-- PARA PASAR A OTRA CUENTA DE SUPABASE: crear el proyecto nuevo y correr este
-- mismo archivo. No hay que tocar nada más (ver docs/GUIA-SUPABASE.md).
-- SI NECESITAS UNA COLUMNA/TABLA NUEVA: agrégala al final con
--   ALTER TABLE ... ADD COLUMN IF NOT EXISTS ...   o   CREATE TABLE IF NOT EXISTS ...
--
-- Tablas (11):
--   usuarios_combustible, permisos_usuarios_combustible  -> acceso al sistema
--   tractores, operarios                                  -> catálogos
--   jornadas_combustible   -> UNA fila por día: medidores M1/M2 + checklist
--   registros_combustible  -> suministros a cada máquina (sin datos de M1/M2)
--   alertas_combustible, notificaciones_combustible       -> alertas y avisos
--   sesiones_combustible, intentos_login_combustible      -> sesiones y anti fuerza bruta
--   auditoria_combustible  -> bitácora INMUTABLE
--   suscripciones_push     -> dispositivos que reciben notificaciones
-- Los soportes (PDF/imagen) van a Supabase Storage (bucket "soportes").
-- ============================================================================

-- --- USUARIOS Y PERMISOS ----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuarios_combustible (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario VARCHAR(80) NOT NULL,
  contrasena VARCHAR(255) NOT NULL,             -- hash scrypt, nunca texto plano
  rol VARCHAR(40) NOT NULL,
  debe_cambiar_contrasena BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
-- Un usuario es único sin importar mayúsculas (Juan = juan).
CREATE UNIQUE INDEX IF NOT EXISTS ux_usuarios_usuario ON usuarios_combustible (LOWER(usuario));

CREATE TABLE IF NOT EXISTS permisos_usuarios_combustible (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios_combustible(id) ON DELETE CASCADE,
  vista VARCHAR(40) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT permiso_unico UNIQUE (usuario_id, vista)
);

-- --- CATÁLOGOS --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tractores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item INTEGER NOT NULL,
  maquina VARCHAR(20) NOT NULL,
  descripcion VARCHAR(150) NOT NULL,
  centro_costo VARCHAR(20) NOT NULL,
  capacidad_galones NUMERIC(12,2) DEFAULT 0,    -- base de las alertas de sobrecapacidad
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO', -- ACTIVO | ANULADO (no se borra)
  motivo_anulacion VARCHAR(255),
  usuario_anulacion VARCHAR(80),
  fecha_anulacion TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_tractores_maquina ON tractores (UPPER(maquina));

CREATE TABLE IF NOT EXISTS operarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  cedula VARCHAR(30) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  motivo_anulacion VARCHAR(255),
  usuario_anulacion VARCHAR(80),
  fecha_anulacion TIMESTAMPTZ
);

-- --- JORNADAS: una por día, con los medidores del surtidor y el checklist ----
-- estado 'abierta'  = hay datos guardados (borrador) pero falta el cierre.
-- estado 'cerrada'  = cierre definitivo (lecturas bloqueadas).
-- La fecha es UNIQUE: nunca puede haber dos jornadas (ni dos cierres) el mismo día.
CREATE TABLE IF NOT EXISTS jornadas_combustible (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL UNIQUE,
  m1_inicial NUMERIC(12,2),
  m1_final NUMERIC(12,2),
  m2_inicial NUMERIC(12,2),
  m2_final NUMERIC(12,2),
  galones_m1 NUMERIC(12,2),
  galones_m2 NUMERIC(12,2),
  total_galones NUMERIC(12,2),
  fuga_biodiesel VARCHAR(20),
  sistema_electrico VARCHAR(30),
  parada_emergencia VARCHAR(30),
  estado VARCHAR(10) NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'cerrada')),
  abierta_por VARCHAR(80),
  abierta_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  actualizada_por VARCHAR(80),
  actualizada_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  cerrada_por VARCHAR(80),
  cerrada_en TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_jornadas_estado ON jornadas_combustible (estado, fecha);

-- --- REGISTROS: suministros a cada máquina ----------------------------------
CREATE TABLE IF NOT EXISTS registros_combustible (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL,
  operario VARCHAR(120),
  cedula VARCHAR(30),
  maquina VARCHAR(80),
  horometro VARCHAR(120),
  cantidad NUMERIC(12,2),
  numero_sai VARCHAR(80),
  firma TEXT,                                   -- imagen de la firma en base64
  observaciones TEXT,
  registrado_por VARCHAR(80),
  registrado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO', -- ACTIVO | ANULADO (no se borra)
  motivo_anulacion VARCHAR(255),
  usuario_anulacion VARCHAR(80),
  fecha_anulacion TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_registros_fecha ON registros_combustible (fecha);
CREATE INDEX IF NOT EXISTS ix_registros_maquina ON registros_combustible (UPPER(maquina));

-- --- ALERTAS Y NOTIFICACIONES -----------------------------------------------
-- Una alerta nace de un registro (registro_id) o de una jornada (jornada_id:
-- checklist pendiente, cierre pendiente).
CREATE TABLE IF NOT EXISTS alertas_combustible (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registro_id INTEGER REFERENCES registros_combustible(id) ON DELETE SET NULL,
  jornada_id INTEGER REFERENCES jornadas_combustible(id) ON DELETE SET NULL,
  fecha DATE NOT NULL,
  maquina VARCHAR(80) NOT NULL,
  operario VARCHAR(120),
  cantidad NUMERIC(12,2) NOT NULL,
  capacidad_galones NUMERIC(12,2) NOT NULL,
  exceso_galones NUMERIC(12,2) NOT NULL,
  observaciones TEXT,
  justificacion TEXT,
  estado VARCHAR(30) DEFAULT 'pendiente',
  justificado_por VARCHAR(80),
  justificado_en TIMESTAMPTZ,
  reporte_nombre VARCHAR(255),
  reporte_ruta VARCHAR(500),                    -- ruta del soporte en Storage ("sb:...")
  reporte_tipo VARCHAR(100),
  tipo_alerta VARCHAR(30) NOT NULL DEFAULT 'sobrecapacidad',
  promedio_galones NUMERIC(12,2),
  porcentaje_sobre_promedio NUMERIC(8,2),
  detalle_alerta VARCHAR(255),
  valor_referencia NUMERIC(12,2),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT alerta_registro_tipo_unico UNIQUE (registro_id, tipo_alerta),
  CONSTRAINT alerta_jornada_tipo_unico UNIQUE (jornada_id, tipo_alerta)
);
CREATE INDEX IF NOT EXISTS ix_alertas_fecha ON alertas_combustible (fecha);

CREATE TABLE IF NOT EXISTS notificaciones_combustible (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alerta_id INTEGER NOT NULL REFERENCES alertas_combustible(id) ON DELETE CASCADE,
  rol VARCHAR(40) NOT NULL,
  titulo VARCHAR(180) NOT NULL,
  mensaje TEXT NOT NULL,
  leida BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  leida_en TIMESTAMPTZ,
  CONSTRAINT notificacion_unica UNIQUE (alerta_id, rol)
);

-- --- SESIONES Y ANTI FUERZA BRUTA -------------------------------------------
-- Se guarda el SHA-256 del token, nunca el token.
CREATE TABLE IF NOT EXISTS sesiones_combustible (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash CHAR(64) NOT NULL UNIQUE,
  usuario_id INTEGER NOT NULL REFERENCES usuarios_combustible(id) ON DELETE CASCADE,
  expira_en TIMESTAMPTZ NOT NULL,
  ultimo_uso TIMESTAMPTZ,
  ip VARCHAR(100),
  agente VARCHAR(255),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_sesiones_expira ON sesiones_combustible (expira_en);

CREATE TABLE IF NOT EXISTS intentos_login_combustible (
  clave VARCHAR(250) PRIMARY KEY,
  intentos INTEGER NOT NULL,
  primer_intento TIMESTAMPTZ NOT NULL
);

-- --- AUDITORÍA (INMUTABLE) --------------------------------------------------
CREATE TABLE IF NOT EXISTS auditoria_combustible (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER REFERENCES usuarios_combustible(id) ON DELETE SET NULL,
  usuario VARCHAR(80),
  rol VARCHAR(40),
  accion VARCHAR(40) NOT NULL,
  modulo VARCHAR(60) NOT NULL,
  registro_id BIGINT,
  detalle JSONB,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS ix_auditoria_fecha ON auditoria_combustible (creado_en);
CREATE INDEX IF NOT EXISTS ix_auditoria_modulo ON auditoria_combustible (modulo);

-- La base de datos misma impide editar o borrar la bitácora (ni con acceso
-- directo). Única excepción: al eliminar un usuario, Postgres pone usuario_id
-- en NULL; el nombre queda guardado en la columna "usuario".
CREATE OR REPLACE FUNCTION auditoria_inmutable() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'La auditoría es inmutable: no se pueden borrar eventos.';
  END IF;
  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.usuario IS DISTINCT FROM OLD.usuario
     OR NEW.rol IS DISTINCT FROM OLD.rol
     OR NEW.accion IS DISTINCT FROM OLD.accion
     OR NEW.modulo IS DISTINCT FROM OLD.modulo
     OR NEW.registro_id IS DISTINCT FROM OLD.registro_id
     OR NEW.detalle IS DISTINCT FROM OLD.detalle
     OR NEW.creado_en IS DISTINCT FROM OLD.creado_en THEN
    RAISE EXCEPTION 'La auditoría es inmutable: no se pueden modificar eventos.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auditoria_inmutable ON auditoria_combustible;
CREATE TRIGGER trg_auditoria_inmutable
  BEFORE UPDATE OR DELETE ON auditoria_combustible
  FOR EACH ROW EXECUTE FUNCTION auditoria_inmutable();

-- --- NOTIFICACIONES PUSH ----------------------------------------------------
-- Un usuario puede tener varios dispositivos (celular, tablet).
CREATE TABLE IF NOT EXISTS suscripciones_push (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios_combustible(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  agente VARCHAR(255),
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- --- SEGURIDAD: RLS ---------------------------------------------------------
-- Supabase publica las tablas por su API REST. Con RLS activo y SIN políticas,
-- esa API no puede leer ni escribir nada. La aplicación entra con la cadena de
-- conexión directa (rol postgres), que no se ve afectada.
ALTER TABLE usuarios_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE permisos_usuarios_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE tractores ENABLE ROW LEVEL SECURITY;
ALTER TABLE operarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE jornadas_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE registros_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE alertas_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificaciones_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE sesiones_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE intentos_login_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria_combustible ENABLE ROW LEVEL SECURITY;
ALTER TABLE suscripciones_push ENABLE ROW LEVEL SECURITY;

-- --- STORAGE: bucket privado para los soportes de alertas -------------------
-- Solo existe en Supabase (esquema "storage"); en otro Postgres se omite.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.schemata WHERE schema_name = 'storage') THEN
    INSERT INTO storage.buckets (id, name, public)
    VALUES ('soportes', 'soportes', FALSE)
    ON CONFLICT (id) DO NOTHING;
  END IF;
END $$;
